token:
  header: Authorization
  secret: abcdefghijklmnopqrstuvwxyz
  expireTime: 60

server:
  port: 8091

xss:
  # ????
  enabled: true
  # ?????????????
  excludes: /system/notice
  # ????
  urlPatterns: /service/*,/controller/*,/security/*

spring:
  application:
    name: data-projects
  # ????
  messages:
    # ?????????
    basename: i18n/messages
  profiles:
    active: dev
  # ????
  servlet:
    multipart:
      # ??????
      max-file-size: 10MB
      # ??????????
      max-request-size: 20MB
  # ????
  devtools:
    restart:
      # ?????
      enabled: true
  data:
    # redis ??
    redis:
      # ??
      host: localhost
      # ??????6379
      port: 6379
      # ?????
      database: 0
      # ??
      password:
      # ??????
      timeout: 10s
      lettuce:
        pool:
          # ???????????
          min-idle: 0
          # ???????????
          max-idle: 8
          # ????????????
          max-active: 8
          # #???????????????????????
          max-wait: -1ms